version: "3.8"

services:
  whisper-api:
    image: ghcr.io/jina-ai/whisper-asr-webservice:latest
    container_name: whisper-api
    ports:
      - "5000:5000"
    environment:
      - ASR_MODEL=medium  # Options: tiny, base, small, medium, large
      - LANG=auto
      - NUM_WORKERS=1
      - BEAM_SIZE=5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
