version: "3.8"

services:
  whisper-api:
    image: ghcr.io/ggerganov/whisper.cpp:latest
    container_name: whisper-api
    command: [ "--threads", "8" ]
    expose:
      - "5000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./razorpay-landing:/usr/share/nginx/html
    depends_on:
      - whisper-api
    restart: unless-stopped
